FROM node:22-alpine

WORKDIR /workspace

ENV NODE_ENV=development

COPY package.json package-lock.json ./
COPY apps/web/package.json ./apps/web/package.json
COPY apps/api/package.json ./apps/api/package.json

RUN npm ci

COPY . .

EXPOSE 3000 3333

CMD ["npm", "run", "dev"]