import type { AnamneseRecord } from "./types";

export const sampleAnamneseRecords: AnamneseRecord[] = [
  {
    id: "sample-anamnese-001",
    code: "ANA-2026-0001",
    status: "finalized",
    createdAt: "2026-06-27T08:30:00.000Z",
    updatedAt: "2026-06-27T09:15:00.000Z",
    finalizedAt: "2026-06-27T09:15:00.000Z",
    patientName: "Marcos Henrique Almeida",
    answers: {
      "nursing-admission": {
        patientName: "Marcos Henrique Almeida",
        birthDate: "1988-04-12",
        age: "38",
        smoker: "Sim",
        usesMedication: "Sim",
        medicationList: "Losartana 50 mg pela manhã. Relata uso eventual de dipirona.",
        medicationAllergy: "Não",
        foodAllergy: "Sim",
        foodAllergyDetails: "Camarão e frutos do mar.",
        hypertension: "Sim",
        diabetes: "Não",
        hepatitis: "Não",
        asthma: "Não",
        consciousnessLevel: ["Consciente", "Orientado", "Ansioso"],
        bloodPressure: "138x88 mmHg",
        temperature: "36,7",
        heartRate: "84",
        respiratoryRate: "18",
        scalp: "Sem alterações",
        eyes: ["Sem alterações"],
        mucosa: "Corada",
        neck: "Sem alterações",
        skin: ["Sem alterações"],
        otherLesion: "Não",
        nutritionalStatus: "Sobrepeso",
        diuresis: "Presente",
        evacuations: "Presente",
        genitalRegion: ["Sem alterações"],
        nursingNotes: "Paciente cooperativo, ansioso no momento da admissão, sem queixas álgicas importantes.",
        nursingDate: "2026-06-27",
        nurseName: "Enf. Camila Rocha",
        coren: "COREN-CE 123456"
      },
      psychological: {
        patient: "Marcos Henrique Almeida",
        admissionDate: "2026-06-27",
        birthDate: "1988-04-12",
        age: "38",
        hd: "Transtorno por uso de álcool - hipótese inicial",
        interviewDate: "2026-06-27",
        interviewTime: "09:00",
        profession: "Motorista",
        currentlyWorking: "Não",
        workRole: "Motorista de aplicativo",
        socialSecurityLeave: "Não",
        sex: "M",
        spouse: "Fernanda Lima Almeida",
        spouseAge: "35",
        education: "Ens. médio",
        substanceUser: "Sim",
        substanceUserDetails: "Álcool e tabaco.",
        hasChildren: "Sim",
        childrenCount: "2",
        childrenTable: {
          "Filho 1": { name: "Lucas", age: "10", profession: "Estudante" },
          "Filho 2": { name: "Mariana", age: "7", profession: "Estudante" }
        },
        fatherName: "João Almeida",
        fatherLifeStatus: "Vivo",
        fatherAge: "66",
        fatherProfession: "Aposentado",
        motherName: "Rita Almeida",
        motherLifeStatus: "Viva",
        motherAge: "62",
        motherProfession: "Costureira",
        hasSiblings: "Sim",
        siblingsCount: "1",
        siblingsTable: {
          "Irmão 1": { name: "Patrícia", age: "34", profession: "Professora" }
        },
        currentHousehold: {
          "Pessoa 1": { name: "Fernanda", age: "35", kinship: "Cônjuge" },
          "Pessoa 2": { name: "Lucas", age: "10", kinship: "Filho" },
          "Pessoa 3": { name: "Mariana", age: "7", kinship: "Filha" }
        },
        religion: "Católica",
        religionPracticing: "Raramente",
        referredBy: "Família",
        admissionType: "Voluntário",
        familyMentalIllness: "Relata tio materno com tratamento prévio para depressão.",
        hospitalizationReasonFamily: "Família relata aumento progressivo do consumo de álcool, faltas no trabalho e conflitos domésticos.",
        mainComplaintPatient: "Paciente refere dificuldade para controlar consumo de álcool aos fins de semana.",
        presentedAspects: ["Problemas de memória", "Uso de substância psicoativa"],
        psychosocialRisks: ["Relações sexuais sem uso de preservativo"],
        suicideAttempt: "Não",
        sexualLife: "Vida sexual ativa",
        policeJusticeInvolvement: "Não",
        takenToPoliceStation: "Não",
        processNotConvicted: "Não",
        convicted: "Não",
        currentlyResponding: "Não",
        servedSentence: "Não",
        drugStartFactor: ["Influência dos amigos ou pressão do grupo", "Curiosidade"],
        drugContinuationFactor: ["Convívio com outros usuários", "Gostou, prazer com o uso"],
        preferredUseTime: ["À noite"],
        psychDrugsTable: {
          Álcool: { startAge: "16", lastUse: "2 dias", frequency: "Diário", quantity: "6 a 8 doses" },
          Tabaco: { startAge: "18", lastUse: "Hoje", frequency: "Diário", quantity: "10 cigarros" }
        },
        drugResources: ["Recurso próprio"],
        drugLosses: "Prejuízo financeiro e afastamento de atividades familiares.",
        financialImpact: "Moderado",
        socialImpact: "Redução do convívio social saudável e conflitos com vizinhos em episódios de intoxicação.",
        familyImpact: "Conflitos conjugais e afastamento dos filhos em alguns períodos.",
        treatmentExpectations: "Reduzir fissura, reorganizar rotina e retomar vínculo familiar.",
        triagistImpression: ["Motivação para o tratamento"],
        psychologistResponsible: "Psicóloga Ana Beatriz - CRP 11/00000"
      },
      "therapeutic-initial": {
        counselorResponsible: "Conselheiro Paulo Nascimento",
        therapeuticDate: "2026-06-27",
        therapeuticPatientName: "Marcos Henrique Almeida",
        therapeuticBirthDate: "1988-04-12",
        therapeuticAge: "38",
        naturalness: "Fortaleza",
        stateUf: "CE",
        city: "Aquiraz",
        maritalStatus: "Casado",
        profession: "Motorista",
        admissionType: "Voluntária",
        insurance: "Particular",
        needsInssLeave: "Não",
        substanceUseHistory: "Relata uso de álcool desde a adolescência, com aumento de frequência nos últimos dois anos. Tabaco em uso diário.",
        otherCompulsion: "Nega compulsões comportamentais relevantes no momento da entrevista.",
        lastUse: "Último uso de álcool há 2 dias, em contexto social; tabaco no dia da admissão.",
        substanceConsumption: {
          Álcool: { last12MonthsFrequency: "Diário", last12MonthsQuantity: "6 a 8 doses", lifetimeFrom: "16 anos", lifetimeTo: "Atual", notes: "Maior consumo à noite." },
          Tabaco: { last12MonthsFrequency: "Diário", last12MonthsQuantity: "10 cigarros", lifetimeFrom: "18 anos", lifetimeTo: "Atual", notes: "Associado ao consumo de álcool." },
          Maconha: { last12MonthsFrequency: "Não usou", last12MonthsQuantity: "", lifetimeFrom: "20 anos", lifetimeTo: "25 anos", notes: "Uso experimental anterior." }
        },
        previousHospitalization: "Não",
        knows12Steps: "Sim",
        psychiatricTreatment: "Não",
        mentalDisorderDiagnosis: "Nega diagnóstico formal prévio.",
        relapseHistory: "Refere tentativas de abstinência sem acompanhamento, com retorno ao consumo em situações sociais.",
        familyHistory: {
          Pai: { quantity: "1", relationship: "Contato semanal, relação estável." },
          Mãe: { quantity: "1", relationship: "Apoio frequente." },
          "Companheiro(a)": { quantity: "1", relationship: "Relação fragilizada por conflitos recentes." },
          "Filho(a)": { quantity: "2", relationship: "Vínculo preservado." }
        },
        partnerRelationship: "Relação com conflitos ligados ao consumo de álcool, mas companheira participa do suporte familiar.",
        partnerUsesSubstance: "Não",
        separationBySubstance: "Não",
        familySubstanceRelationship: "Família reconhece o uso como problema e aceita participar de orientações.",
        familyAbuse: "Sim",
        familyAbuseWho: "Tio materno com histórico de alcoolismo.",
        familyCriminalProblems: "Não",
        familySupport: "Conta com apoio parcial",
        externalReference: "Fernanda Lima Almeida - esposa",
        violenceAggression: "Não",
        livesWith: ["Companheiro(a)", "Filho(a)"],
        livesWithNotes: "Mora com esposa e dois filhos.",
        mutualHelpGroups: "Raramente",
        spirituality: "Raramente",
        contactWithUsers: "Ocasionalmente",
        educationLevel: "Ensino Médio",
        educationCompletion: "Completo",
        currentlyEmployed: "Não",
        incomeSource: "Apoio da esposa e trabalhos eventuais.",
        consentPatientName: "Marcos Henrique Almeida",
        consentCityDate: "Aquiraz, 27 de junho de 2026",
        patientSignature: "Marcos Henrique Almeida",
        counselorSignature: "Conselheiro Paulo Nascimento"
      }
    }
  },
  {
    id: "sample-anamnese-002",
    code: "ANA-2026-0002",
    status: "draft",
    createdAt: "2026-06-27T10:20:00.000Z",
    updatedAt: "2026-06-27T10:45:00.000Z",
    patientName: "Renata Sousa Martins",
    answers: {
      "nursing-admission": {
        patientName: "Renata Sousa Martins",
        birthDate: "1995-09-03",
        age: "30",
        smoker: "Não",
        usesMedication: "Sim",
        medicationList: "Sertralina 50 mg, em uso irregular.",
        medicationAllergy: "Sim",
        medicationAllergyDetails: "Relata alergia a penicilina.",
        foodAllergy: "Não",
        hypertension: "Não",
        diabetes: "Não",
        hepatitis: "Não",
        asthma: "Sim",
        consciousnessLevel: ["Consciente", "Orientado", "Ansioso"],
        bloodPressure: "112x72 mmHg",
        temperature: "36,4",
        heartRate: "92",
        respiratoryRate: "20",
        eyes: ["Sem alterações"],
        mucosa: "Corada",
        nutritionalStatus: "Nutrido",
        nursingNotes: "Rascunho de admissão. Aguardando fechamento do atendimento de enfermagem.",
        nursingDate: "2026-06-27",
        nurseName: "Enf. Bruno Cavalcante"
      },
      psychological: {
        patient: "Renata Sousa Martins",
        admissionDate: "2026-06-27",
        birthDate: "1995-09-03",
        age: "30",
        interviewDate: "2026-06-27",
        interviewTime: "10:30",
        profession: "Atendente",
        currentlyWorking: "Sim",
        socialSecurityLeave: "Não",
        sex: "F",
        education: "Ens. médio",
        substanceUser: "Sim",
        substanceUserDetails: "Uso episódico de álcool e ansiolítico sem prescrição em períodos de crise.",
        hasChildren: "Não",
        motherName: "Luciana Sousa",
        motherLifeStatus: "Viva",
        religion: "Evangélica",
        religionPracticing: "Periodicamente",
        referredBy: "Procura espontânea com apoio de amiga",
        admissionType: "Voluntário",
        mainComplaintPatient: "Relata ansiedade intensa, insônia e episódios de uso abusivo em fins de semana.",
        presentedAspects: ["Problemas de atenção", "Dificuldades de relacionamento", "Uso de substância psicoativa"],
        psychosocialRisks: ["Teve ideação suicida"],
        suicideAttempt: "Não",
        policeJusticeInvolvement: "Não",
        preferredUseTime: ["À noite"],
        psychDrugsTable: {
          Álcool: { startAge: "17", lastUse: "5 dias", frequency: "Semanal", quantity: "Variável" },
          Sedativos: { startAge: "29", lastUse: "10 dias", frequency: "Eventual", quantity: "1 comprimido" }
        },
        financialImpact: "Discreto",
        treatmentExpectations: "Controlar ansiedade e evitar uso sem orientação médica."
      },
      "therapeutic-initial": {
        counselorResponsible: "Conselheiro Paulo Nascimento",
        therapeuticDate: "2026-06-27",
        therapeuticPatientName: "Renata Sousa Martins",
        therapeuticBirthDate: "1995-09-03",
        therapeuticAge: "30",
        naturalness: "Caucaia",
        stateUf: "CE",
        city: "Fortaleza",
        maritalStatus: "Solteiro",
        profession: "Atendente",
        admissionType: "Voluntária",
        insurance: "Convênio Vida Plena",
        needsInssLeave: "Sim",
        substanceUseHistory: "Uso episódico de álcool e uso eventual de ansiolítico sem prescrição.",
        otherCompulsion: "Relata compulsão por compras em momentos de ansiedade, ainda em investigação.",
        lastUse: "Álcool há 5 dias; sedativo há aproximadamente 10 dias.",
        substanceConsumption: {
          Álcool: { last12MonthsFrequency: "Semanal", last12MonthsQuantity: "Variável", lifetimeFrom: "17 anos", lifetimeTo: "Atual", notes: "Maior risco em fins de semana." },
          "Medicamentos sem prescrição": { last12MonthsFrequency: "Ocasional", last12MonthsQuantity: "1 comprimido", lifetimeFrom: "29 anos", lifetimeTo: "Atual", notes: "Usa quando está sem dormir." }
        },
        previousHospitalization: "Não",
        psychiatricTreatment: "Sim",
        psychiatricReason: "Ansiedade e insônia.",
        mentalDisorderDiagnosis: "Relata diagnóstico prévio de ansiedade, sem laudo apresentado.",
        livesWith: ["Familiares"],
        mutualHelpGroups: "Não participa",
        spirituality: "Periodicamente",
        contactWithUsers: "Raramente",
        educationLevel: "Ensino Médio",
        educationCompletion: "Completo",
        currentlyEmployed: "Sim",
        incomeSource: "Salário próprio."
      }
    }
  },
  {
    id: "sample-anamnese-003",
    code: "ANA-2026-0003",
    status: "finalized",
    createdAt: "2026-06-26T13:10:00.000Z",
    updatedAt: "2026-06-26T14:05:00.000Z",
    finalizedAt: "2026-06-26T14:05:00.000Z",
    patientName: "Carlos Eduardo Pereira",
    answers: {
      "nursing-admission": {
        patientName: "Carlos Eduardo Pereira",
        birthDate: "1979-12-21",
        age: "46",
        smoker: "Sim",
        usesMedication: "Não",
        medicationAllergy: "Não",
        foodAllergy: "Não",
        hypertension: "Não",
        diabetes: "Não",
        hepatitis: "Não",
        asthma: "Não",
        consciousnessLevel: ["Consciente", "Orientado", "Calmo"],
        bloodPressure: "126x78 mmHg",
        temperature: "36,5",
        heartRate: "76",
        respiratoryRate: "17",
        scalp: "Sem alterações",
        eyes: ["Sem alterações"],
        mucosa: "Corada",
        neck: "Sem alterações",
        skin: ["1 hematoma"],
        otherLesion: "Sim",
        otherLesionDetails: "Pequena escoriação em antebraço direito, sem sinais flogísticos.",
        nutritionalStatus: "Nutrido",
        diuresis: "Presente",
        evacuations: "Presente",
        genitalRegion: ["Sem alterações"],
        nursingNotes: "Admissão sem intercorrências. Orientado quanto à rotina inicial.",
        nursingDate: "2026-06-26",
        nurseName: "Enf. Camila Rocha",
        coren: "COREN-CE 123456"
      },
      psychological: {
        patient: "Carlos Eduardo Pereira",
        admissionDate: "2026-06-26",
        birthDate: "1979-12-21",
        age: "46",
        hd: "Transtorno por uso de cocaína - hipótese inicial",
        interviewDate: "2026-06-26",
        interviewTime: "13:40",
        profession: "Comerciante",
        currentlyWorking: "Sim",
        workRole: "Proprietário de pequeno comércio",
        socialSecurityLeave: "Não",
        sex: "M",
        education: "Ens. superior",
        substanceUser: "Sim",
        substanceUserDetails: "Cocaína, álcool e tabaco.",
        hasChildren: "Sim",
        childrenCount: "1",
        childrenTable: {
          "Filho 1": { name: "Eduarda", age: "15", profession: "Estudante" }
        },
        fatherName: "Antônio Pereira",
        fatherLifeStatus: "Falecido",
        motherName: "Maria das Dores Pereira",
        motherLifeStatus: "Viva",
        hasSiblings: "Sim",
        siblingsCount: "2",
        religion: "Sem religião declarada",
        religionPracticing: "Não",
        referredBy: "Encaminhamento familiar",
        admissionType: "Voluntário",
        familyMentalIllness: "Nega conhecimento de doença mental familiar.",
        hospitalizationReasonFamily: "Família relata períodos de ausência, prejuízo financeiro e irritabilidade associados ao uso.",
        mainComplaintPatient: "Paciente refere perda de controle em períodos de estresse no trabalho.",
        presentedAspects: ["Problemas de atenção", "Queixas sobre agressividade", "Uso de substância psicoativa"],
        psychosocialRisks: ["Relações sexuais com várias pessoas em curto espaço de tempo", "Relações sexuais sem uso de preservativo"],
        suicideAttempt: "Não",
        sexualLife: "Vida sexual ativa",
        policeJusticeInvolvement: "Sim",
        takenToPoliceStation: "Sim",
        processNotConvicted: "Sim",
        convicted: "Não",
        currentlyResponding: "Não",
        servedSentence: "Não",
        drugStartFactor: ["Curiosidade", "Ansiedade ou nervosismo"],
        drugContinuationFactor: ["Tornou-se dependente", "Dificuldades de se relacionar"],
        preferredUseTime: ["Tanto faz"],
        psychDrugsTable: {
          Cocaína: { startAge: "24", lastUse: "1 dia", frequency: "3x semana", quantity: "Variável" },
          Álcool: { startAge: "15", lastUse: "1 dia", frequency: "4x semana", quantity: "4 doses" },
          Tabaco: { startAge: "16", lastUse: "Hoje", frequency: "Diário", quantity: "15 cigarros" }
        },
        drugResources: ["Recurso próprio", "Atividades ilegais"],
        drugLosses: "Endividamento, conflitos familiares e perda de contratos comerciais.",
        financialImpact: "Grave",
        socialImpact: "Afastamento de amigos que não usam substâncias e aproximação de rede de risco.",
        familyImpact: "Separação recente e contato reduzido com a filha.",
        treatmentExpectations: "Reconstruir rotina de trabalho, reduzir fissura e restabelecer vínculo familiar.",
        triagistImpression: ["Motivação para o tratamento", "Outros"],
        triagistOther: "Paciente verbaliza ambivalência, mas aceita permanecer para avaliação inicial.",
        psychologistResponsible: "Psicóloga Ana Beatriz - CRP 11/00000"
      },
      "therapeutic-initial": {
        counselorResponsible: "Conselheiro Paulo Nascimento",
        therapeuticDate: "2026-06-26",
        therapeuticPatientName: "Carlos Eduardo Pereira",
        therapeuticBirthDate: "1979-12-21",
        therapeuticAge: "46",
        naturalness: "Sobral",
        stateUf: "CE",
        city: "Aquiraz",
        maritalStatus: "Divorciado",
        profession: "Comerciante",
        admissionType: "Voluntária",
        insurance: "Particular",
        needsInssLeave: "Não",
        substanceUseHistory: "Uso de cocaína, álcool e tabaco. Refere perda de controle associada a estresse laboral.",
        otherCompulsion: "Relata comportamento de risco financeiro em períodos de uso, sem outro padrão compulsivo formalizado.",
        lastUse: "Cocaína e álcool há 1 dia; tabaco no dia da entrevista.",
        substanceConsumption: {
          Cocaína: { last12MonthsFrequency: "3x semana", last12MonthsQuantity: "Variável", lifetimeFrom: "24 anos", lifetimeTo: "Atual", notes: "Uso associado a estresse e rede social de risco." },
          Álcool: { last12MonthsFrequency: "4x semana", last12MonthsQuantity: "4 doses", lifetimeFrom: "15 anos", lifetimeTo: "Atual", notes: "Frequentemente associado à cocaína." },
          Tabaco: { last12MonthsFrequency: "Diário", last12MonthsQuantity: "15 cigarros", lifetimeFrom: "16 anos", lifetimeTo: "Atual", notes: "Mantém uso regular." }
        },
        previousHospitalization: "Sim",
        previousHospitalizationCount: "1",
        treatmentPeriodFrom: "2024-03-01",
        treatmentPeriodTo: "2024-04-20",
        postTreatmentAbstinence: "Aproximadamente 5 meses",
        treatmentLocation: "Comunidade terapêutica em outro município.",
        dischargeReason: "Alta solicitada pelo paciente antes do prazo sugerido.",
        knows12Steps: "Sim",
        psychiatricTreatment: "Não",
        relapseHistory: "Recaída após retorno ao trabalho e contato com antigos colegas de uso.",
        familyHistory: {
          Pai: { quantity: "1", relationship: "Falecido, histórico de relação distante." },
          Mãe: { quantity: "1", relationship: "Contato preservado." },
          "Companheiro(a)": { quantity: "0", relationship: "Separação recente." },
          "Filho(a)": { quantity: "1", relationship: "Contato reduzido." }
        },
        partnerRelationship: "Separado recentemente, com conflitos relacionados ao uso e endividamento.",
        partnerUsesSubstance: "Não",
        separationBySubstance: "Sim",
        separationDetails: "Separação ocorreu após episódios de ausência e prejuízo financeiro.",
        familySubstanceRelationship: "Família demonstra cansaço, mas mantém disponibilidade para participação orientada.",
        familyAbuse: "Não",
        familyCriminalProblems: "Não",
        familySupport: "Conta com apoio parcial",
        externalReference: "Maria das Dores Pereira - mãe",
        violenceAggression: "Sim",
        familyNotes: "Relata discussões verbais intensas, nega agressão física recente.",
        livesWith: ["Sozinho(a)"],
        livesWithNotes: "Mora sozinho desde a separação.",
        mutualHelpGroups: "Raramente",
        spirituality: "Não participa",
        contactWithUsers: "Frequentemente",
        educationLevel: "Superior",
        educationCompletion: "Completo",
        currentlyEmployed: "Sim",
        incomeSource: "Renda do comércio e auxílio eventual da mãe.",
        consentPatientName: "Carlos Eduardo Pereira",
        consentCityDate: "Aquiraz, 26 de junho de 2026",
        patientSignature: "Carlos Eduardo Pereira",
        counselorSignature: "Conselheiro Paulo Nascimento"
      }
    }
  }
];